---
Resources:
  WebRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName:
          "Fn::GetAtt":
            - CloudFrontDistribution
            - DomainName
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
      HostedZoneId: ${self:custom.config.hostedZoneId}
      Name: "${self:custom.config.domain}"
      Type: A

  WebIPV6RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName:
          "Fn::GetAtt":
            - CloudFrontDistribution
            - DomainName
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
      HostedZoneId: "${self:custom.config.hostedZoneId}"
      Name: "${self:custom.config.domain}"
      Type: AAAA

  RedirectRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName:
          "Fn::GetAtt":
            - RedirectCloudFrontDistribution
            - DomainName
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
      HostedZoneId: ${self:custom.config.hostedZoneId}
      Name: "www.${self:custom.config.domain}"
      Type: A

  RedirectIPV6RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName:
          "Fn::GetAtt":
            - RedirectCloudFrontDistribution
            - DomainName
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
      HostedZoneId: ${self:custom.config.hostedZoneId}
      Name: "www.${self:custom.config.domain}"
      Type: AAAA
